Change recommended drawing library
Shopify/packwerk pull request #385
Opened 2024-01-16 15:39 UTC by euglena1215

## What are you trying to accomplish?

Change the drawing library introduced as the packwerk ecosystem from [graphwerk](https://github.com/samuelgiles/graphwerk) gem to [visualize_packs](https://github.com/rubyatscale/visualize_packs) gem.

## What approach did you choose and why?

The graphwerk gem is introduced as part of the ecosystem, but the graphwerk gem has not been maintained recently.

Since the visualize_packs gem is more actively maintained, I thought it would be appropriate to introduce the visualize_packs gem as part of the ecosystem.

## What should reviewers focus on?

Please determine if the visualize_packs gem is appropriate as a recommended drawing library.

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [x] Non-breaking change (a change that doesn't alter functionality - i.e., code refactor, configs, etc.)

## Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] It is safe to rollback this change.

2024-01-16 15:43 UTC, euglena1215 commented
I have signed the CLA!

2024-01-20 01:37 UTC, gmcgibbon requested changes
Thank you for your contribution, but this cannot be accepted. It is unfortunate that graphwerk hasn't been maintained recently, but I don't want to imply that one needs to use "packs" for visualization. It adds many features on top of Packwerk, some of which the maintainers of Packwerk disagree with.

2024-01-21 01:22 UTC, euglena1215 commented
@gmcgibbon 
Thanks for the review. I did not know that the visualize_packs gem depends on the directory name "packs".
So I can understand why it is not accepetable.

2024-01-21 01:22 UTC, closed without merging

2024-01-22 22:45 UTC, alexevanczuk commented
Hey @euglena1215 just wanted to chime in to say that `packs-rails` and the `packs` spec in general defaults to `./packs` as the root dir, but the pack directories are totally configurable. Only saying that to clear up any misconceptions!